name: Fake Approvals

on:
  pull_request:
    types: [labeled, unlabeled, opened]

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approved label
        if: contains(github.event.pull_request.labels.*.name, 'approved')
        run: echo "PR is approved!"
      - name: Fail if not approved
        if: "!contains(github.event.pull_request.labels.*.name, 'approved')"
        run: echo "PR is not approved!" && exit 1
